# Generated by Django 2.0 on 2019-08-31 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mesaj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='publishing_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='yayımlanma_tarihi'),
            preserve_default=False,
        ),
    ]
