# Generated by Django 2.0 on 2019-09-13 15:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesaj', '0003_auto_20190908_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mesaj',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
