# Generated by Django 2.0 on 2019-08-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etkinlik',
            name='asistan',
        ),
        migrations.RemoveField(
            model_name='etkinlik',
            name='ogrenci',
        ),
        migrations.RemoveField(
            model_name='etkinlik',
            name='ogretmen',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bireysel_odulu',
        ),
        migrations.RemoveField(
            model_name='student',
            name='kitap',
        ),
        migrations.RemoveField(
            model_name='student',
            name='no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sayfa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='takim',
        ),
        migrations.RemoveField(
            model_name='student',
            name='takim_odulu',
        ),
        migrations.DeleteModel(
            name='Etkinlik',
        ),
        migrations.DeleteModel(
            name='Kitap',
        ),
    ]
