# Generated by Django 2.0 on 2019-07-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slayt',
            name='isim',
            field=models.CharField(blank=True, max_length=50, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='slayt',
            name='yazı',
            field=models.CharField(blank=True, max_length=200, verbose_name='Yazı'),
        ),
    ]
