# Generated by Django 2.0 on 2020-10-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0002_auto_20200211_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genel',
            options={'ordering': ['sira'], 'verbose_name': 'Genel-Konu', 'verbose_name_plural': 'Genel-Konular'},
        ),
    ]
