# Generated by Django 2.0 on 2019-07-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0002_auto_20190622_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenkFont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, choices=[('bg-primary', 'mavi'), ('bg-secondary', 'gri'), ('bg-success', 'yeşil'), ('bg-danger', 'kırmızı'), ('bg-warning', 'turuncu'), ('bg-info', 'açık mavi'), ('bg-light', 'ince beyaz'), ('bg-dark', 'koyu siyah'), ('bg-white', 'kalın beyaz'), ('bg-transparent', 'ince siyah')], max_length=30, verbose_name='komple sayfanın arka plan rengi')),
                ('kategorilerim_yazı_rengi', models.CharField(blank=True, choices=[('text-primary', 'mavi'), ('text-secondary', 'gri'), ('text-success', 'yeşil'), ('text-danger', 'kırmızı'), ('text-warning', 'turuncu'), ('text-info', 'açık mavi'), ('text-light', 'ince beyaz'), ('text-dark', 'koyu siyah'), ('text-body', 'az koyu siyah'), ('text-muted', 'sönük gri'), ('text-white', 'kalın beyaz'), ('text-black-50', 'ince siyah'), ('text-white-50', 'kalın gri')], max_length=30, verbose_name='KATEGORİLERİM başlığının yazı rengi')),
                ('kategorilerim_yazısı_arka_plan_rengi', models.CharField(blank=True, choices=[('bg-primary', 'mavi'), ('bg-secondary', 'gri'), ('bg-success', 'yeşil'), ('bg-danger', 'kırmızı'), ('bg-warning', 'turuncu'), ('bg-info', 'açık mavi'), ('bg-light', 'ince beyaz'), ('bg-dark', 'koyu siyah'), ('bg-white', 'kalın beyaz'), ('bg-transparent', 'ince siyah')], max_length=30, verbose_name='KATEGORİLERİM başlığının arka plan rengi')),
                ('kategorilerim_arka_plan_rengi', models.CharField(blank=True, choices=[('bg-primary', 'mavi'), ('bg-secondary', 'gri'), ('bg-success', 'yeşil'), ('bg-danger', 'kırmızı'), ('bg-warning', 'turuncu'), ('bg-info', 'açık mavi'), ('bg-light', 'ince beyaz'), ('bg-dark', 'koyu siyah'), ('bg-white', 'kalın beyaz'), ('bg-transparent', 'ince siyah')], max_length=30, verbose_name='KATEGORİLERİM bölümünün arka plan rengi')),
                ('kategorilerim_yazı_boyutu', models.CharField(blank=True, choices=[(8, 0), (10, 10), (12, 15), (14, 20), (16, 25), (18, 30), (20, 35), (22, 40), (24, 45)], max_length=30, verbose_name='KATEGORİLERİM başlığının yazı büyüklğü')),
                ('urunler_yazı_boyutu', models.CharField(blank=True, choices=[(8, 0), (10, 10), (12, 15), (14, 20), (16, 25), (18, 30), (20, 35), (22, 40), (24, 45)], max_length=30, verbose_name='Ürünler başlığının yazı büyüklğü')),
                ('urunler_arka_plan_rengi', models.CharField(blank=True, choices=[('bg-primary', 'mavi'), ('bg-secondary', 'gri'), ('bg-success', 'yeşil'), ('bg-danger', 'kırmızı'), ('bg-warning', 'turuncu'), ('bg-info', 'açık mavi'), ('bg-light', 'ince beyaz'), ('bg-dark', 'koyu siyah'), ('bg-white', 'kalın beyaz'), ('bg-transparent', 'ince siyah')], max_length=30, verbose_name='Ürünler başlığının arka plan rengi')),
                ('ilk_üç_button', models.CharField(blank=True, choices=[('btn-primary', 'mavi'), ('btn-secondary', 'gri'), ('btn-success', 'yeşil'), ('btn-danger', 'kırmızı'), ('btn-warning', 'turuncu'), ('btn-info', 'açık mavi'), ('btn-light', 'ince beyaz'), ('btn-dark', 'koyu siyah'), ('btn-white', 'kalın beyaz'), ('btn-link', 'sadece mavi link')], max_length=30, verbose_name="ürün kategorilerindeki ilk üç button'un rengi")),
                ('dördüncü_button', models.CharField(blank=True, choices=[('btn-primary', 'mavi'), ('btn-secondary', 'gri'), ('btn-success', 'yeşil'), ('btn-danger', 'kırmızı'), ('btn-warning', 'turuncu'), ('btn-info', 'açık mavi'), ('btn-light', 'ince beyaz'), ('btn-dark', 'koyu siyah'), ('btn-white', 'kalın beyaz'), ('btn-link', 'sadece mavi link')], max_length=30, verbose_name="ürün kategorilerindeki dördüncü button'un rengi")),
                ('beşinci_button', models.CharField(blank=True, choices=[('btn-primary', 'mavi'), ('btn-secondary', 'gri'), ('btn-success', 'yeşil'), ('btn-danger', 'kırmızı'), ('btn-warning', 'turuncu'), ('btn-info', 'açık mavi'), ('btn-light', 'ince beyaz'), ('btn-dark', 'koyu siyah'), ('btn-white', 'kalın beyaz'), ('btn-link', 'sadece mavi link')], max_length=30, verbose_name="ürün kategorilerindeki beşinci button'un rengi")),
                ('altıncı_button', models.CharField(blank=True, choices=[('btn-primary', 'mavi'), ('btn-secondary', 'gri'), ('btn-success', 'yeşil'), ('btn-danger', 'kırmızı'), ('btn-warning', 'turuncu'), ('btn-info', 'açık mavi'), ('btn-light', 'ince beyaz'), ('btn-dark', 'koyu siyah'), ('btn-white', 'kalın beyaz'), ('btn-link', 'sadece mavi link')], max_length=30, verbose_name="ürün kategorilerindeki altıncı button'un rengi")),
                ('yedinci_button', models.CharField(blank=True, choices=[('btn-primary', 'mavi'), ('btn-secondary', 'gri'), ('btn-success', 'yeşil'), ('btn-danger', 'kırmızı'), ('btn-warning', 'turuncu'), ('btn-info', 'açık mavi'), ('btn-light', 'ince beyaz'), ('btn-dark', 'koyu siyah'), ('btn-white', 'kalın beyaz'), ('btn-link', 'sadece mavi link')], max_length=30, verbose_name="ürün kategorilerindeki yedinci button'un rengi")),
                ('isim', models.CharField(default='Site Geneli Özellikler', max_length=50)),
                ('navbardaki_yazı', models.CharField(max_length=250, verbose_name='Navbardaki yazı')),
                ('site_adı', models.CharField(default='Kitap Turnuvası', max_length=250, verbose_name='Sitenin Adı')),
            ],
            options={
                'verbose_name': 'Renk-ve-Yazı',
                'verbose_name_plural': 'Renk-ve-Yazılar',
            },
        ),
    ]
