# Generated by Django 2.0 on 2019-08-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0002_auto_20190719_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renkfont',
            name='cep_telefonu',
            field=models.CharField(default='0505 763 63 81', max_length=50, verbose_name='Cep Telefonu'),
        ),
    ]
