# Generated by Django 2.0 on 2019-08-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0003_auto_20190801_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokuman',
            name='aktif',
            field=models.BooleanField(default=False, verbose_name='aktif mi'),
        ),
        migrations.AddField(
            model_name='dokuman',
            name='sira',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama Sayısı'),
        ),
    ]
