# Generated by Django 2.0 on 2019-07-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0004_auto_20190706_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renkfont',
            name='navbardaki_yazı',
            field=models.CharField(default='blabla', max_length=250, verbose_name='Navbardaki yazı'),
        ),
    ]
