# Generated by Django 2.0 on 2019-08-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0006_auto_20190807_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renkfont',
            name='altıncı_button',
        ),
        migrations.RemoveField(
            model_name='renkfont',
            name='beşinci_button',
        ),
        migrations.RemoveField(
            model_name='renkfont',
            name='body',
        ),
        migrations.RemoveField(
            model_name='renkfont',
            name='dördüncü_button',
        ),
        migrations.RemoveField(
            model_name='renkfont',
            name='ilk_üç_button',
        ),
        migrations.RemoveField(
            model_name='renkfont',
            name='sekizinci_button',
        ),
        migrations.RemoveField(
            model_name='renkfont',
            name='yedinci_button',
        ),
    ]
