# Generated by Django 2.0 on 2019-07-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0006_auto_20190706_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='renkfont',
            name='cep_telefonu',
            field=models.CharField(default='Cep Telefonu', max_length=50, verbose_name='Sitenin Adı'),
        ),
    ]
