# Generated by Django 2.0 on 2019-08-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0007_auto_20190815_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RenkFont',
        ),
    ]
