# Generated by Django 2.0 on 2019-07-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0007_renkfont_cep_telefonu'),
    ]

    operations = [
        migrations.AddField(
            model_name='renkfont',
            name='buttonlar_yazı_büyüklüğü',
            field=models.CharField(blank=True, choices=[('8', 8), ('10', 10), ('12', 12), ('14', 14), ('16', 16), ('18', 18), ('20', 20), ('22', 22), ('24', 24)], max_length=30, verbose_name='Kategori isimlerinin yazı büyüklğü'),
        ),
        migrations.AddField(
            model_name='renkfont',
            name='urunler_yazı_büyüklüğü',
            field=models.CharField(blank=True, choices=[('8', 8), ('10', 10), ('12', 12), ('14', 14), ('16', 16), ('18', 18), ('20', 20), ('22', 22), ('24', 24)], max_length=30, verbose_name='Ürün isimlerinin yazı büyüklğü'),
        ),
    ]
