# Generated by Django 2.0 on 2019-07-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0008_auto_20190706_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renkfont',
            name='cep_telefonu',
            field=models.CharField(default='0505 763 63 81', max_length=50, verbose_name='Sitenin Adı'),
        ),
        migrations.AlterField(
            model_name='renkfont',
            name='navbardaki_yazı',
            field=models.CharField(default='KİTAP OKUMA HEDEFİNİZE PLANLI ÇÖZÜM', max_length=250, verbose_name='Navbardaki yazı'),
        ),
    ]
