# Generated by Django 2.0 on 2019-08-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('sıralama_sayısı',), 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='resim',
            options={'ordering': ('sıralama_sayısı', 'isim'), 'verbose_name': 'Resim-Grubu', 'verbose_name_plural': 'Resim-Grupları'},
        ),
        migrations.AddField(
            model_name='resim',
            name='sıralama_sayısı',
            field=models.PositiveIntegerField(default=0, verbose_name='Anasayfa Sıralama Sayısı'),
        ),
    ]
