# Generated by Django 2.0 on 2019-08-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Gerçek Kategori Resmi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Küçültülmüş Kategori Resmi'),
        ),
    ]
