# Generated by Django 2.0 on 2019-08-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190815_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='anacategory',
            name='arka_plan_renk',
            field=models.CharField(choices=[('btn-primary', 'mavi'), ('btn-secondary', 'gri'), ('btn-success', 'yeşil'), ('btn-danger', 'kırmızı'), ('btn-warning', 'turuncu'), ('btn-info', 'açık mavi'), ('btn-light', 'ince beyaz'), ('btn-dark', 'koyu siyah'), ('btn-white', 'kalın beyaz'), ('btn-link', 'sadece mavi link')], default='btn-primary', max_length=50, verbose_name='Anakategori arka plan rengi'),
        ),
    ]
