# Generated by Django 2.0 on 2019-08-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190823_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resim',
            name='sıralama_sayısı',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama Sayısı'),
        ),
    ]
