# Generated by Django 2.0 on 2019-06-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190622_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d', verbose_name='resim'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ogrenci_sayisi',
            field=models.CharField(choices=[('a', 10), ('b', 15), ('c', 20), ('d', 25), ('e', 30), ('f', 35), ('g', 40), ('h', 45)], max_length=1),
        ),
    ]
