# Generated by Django 2.0 on 2019-06-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190625_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='odul',
            field=models.BooleanField(default=False, verbose_name='Madalyalı Madalyasız?'),
        ),
    ]
