# Generated by Django 2.0 on 2019-06-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_odul'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='resim adı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='resim')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='resimler',
            field=models.ManyToManyField(blank=True, to='shop.Resim'),
        ),
    ]
