# Generated by Django 2.0 on 2019-06-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190627_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sayi',), 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AddField(
            model_name='category',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Madalyalı Resim '),
        ),
        migrations.AddField(
            model_name='category',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Madalyalı Resim'),
        ),
        migrations.AddField(
            model_name='category',
            name='sayi',
            field=models.PositiveIntegerField(default=1, verbose_name='Sıralama Sayısı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ürün resim'),
        ),
        migrations.AlterField(
            model_name='product',
            name='resimler',
            field=models.ManyToManyField(blank=True, to='shop.Resim', verbose_name='Nasıl Uygulanır Resimleri'),
        ),
    ]
