# Generated by Django 2.0 on 2019-06-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190627_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
    ]
