# Generated by Django 2.0 on 2019-06-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_category_aktif'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sayfa_sayısı',
            field=models.CharField(choices=[('a', 1500), ('b', 2500)], default=1, max_length=1, verbose_name='sayfa sayısı'),
            preserve_default=False,
        ),
    ]
