# Generated by Django 2.0 on 2019-06-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_sayfa_sayısı'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='agırlık',
            field=models.PositiveIntegerField(default=0, verbose_name='Ağırlık'),
        ),
    ]
