# Generated by Django 2.0 on 2019-06-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_agırlık'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ogrenci',
            field=models.BooleanField(default=True, help_text='Bireyselse kutucuktaki tik kaldırılacaktır.', verbose_name='Grup mu?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Madalyasız Resim'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sayfa_sayısı',
            field=models.CharField(choices=[('a', 0), ('a', 1000), ('b', 1500), ('c', 2500)], max_length=1, verbose_name='sayfa sayısı'),
        ),
    ]
