# Generated by Django 2.0 on 2019-06-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20190628_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ogrenci_sayisi',
            field=models.CharField(blank=True, choices=[('a', 10), ('b', 15), ('c', 20), ('d', 25), ('e', 30), ('f', 35), ('g', 40), ('h', 45)], max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='sayfa_sayısı',
            field=models.CharField(blank=True, choices=[('a', 0), ('a', 1000), ('b', 1500), ('c', 2500)], max_length=1, verbose_name='sayfa sayısı'),
        ),
    ]
