# Generated by Django 2.0 on 2019-06-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20190628_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='kategori adı')),
                ('sayfa_durumu', models.BooleanField(verbose_name='Sayfa Sayısı Var mı?')),
                ('bireysel_mi', models.BooleanField(verbose_name='Bireysel mi')),
                ('sadece_madalyalı_mı', models.BooleanField(verbose_name='Etkinliksiz madalyalı mı')),
                ('sıralama_sayısı', models.PositiveIntegerField(verbose_name='Sıralama Sayısı')),
                ('aktif', models.BooleanField(verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Ana-Kategori',
                'verbose_name_plural': 'Ana-Kategoriler',
                'ordering': ('sıralama_sayısı',),
            },
        ),
        migrations.CreateModel(
            name='TekliResim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='resim adı')),
                ('image1', models.ImageField(upload_to='', verbose_name='resim')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='aktif',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ogrenci',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='odul',
        ),
        migrations.RemoveField(
            model_name='product',
            name='resimler',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sayfa_sayısı',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='resim',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='madalyalı_mı',
            field=models.BooleanField(default=1, verbose_name='Madalyalı mı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='nasıl_uygulanır_resimleri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nasil', to='shop.Resim', verbose_name='Nasıl Uygulanır Resimleri'),
        ),
        migrations.AddField(
            model_name='category',
            name='odul_buttonu_resimleri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odul', to='shop.Resim', verbose_name='Kişiye özel Ödül Butonu Resimleri'),
        ),
        migrations.AddField(
            model_name='category',
            name='sayfa_sayısı',
            field=models.CharField(choices=[('a', 0), ('a', 1000), ('b', 1500), ('c', 2500)], default=1, max_length=1, verbose_name='sayfa sayısı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Kategori Resmi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ogrenci_sayisi',
            field=models.CharField(choices=[('a', 0), ('b', 10), ('c', 15), ('d', 20), ('e', 25), ('f', 30), ('g', 35), ('h', 40), ('i', 45)], max_length=1),
        ),
        migrations.AddField(
            model_name='category',
            name='ana_kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.AnaCategory', verbose_name='Ana Kategori'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resim',
            name='resimler',
            field=models.ManyToManyField(blank=True, to='shop.TekliResim', verbose_name='resimler'),
        ),
    ]
