# Generated by Django 2.0 on 2019-06-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20190629_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anacategory',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='kategori adı'),
        ),
    ]
