# Generated by Django 2.0 on 2019-06-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20190629_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='anacategory',
            name='slug',
            field=models.SlugField(default=1, max_length=150, verbose_name='internet adresi'),
            preserve_default=False,
        ),
    ]
