# Generated by Django 2.0 on 2019-06-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_anacategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anacategory',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='internet adresi'),
        ),
    ]
