# Generated by Django 2.0 on 2019-07-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20190629_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resim',
            options={'ordering': ('isim',), 'verbose_name': 'Resim-Grubu', 'verbose_name_plural': 'Resim-Grupları'},
        ),
        migrations.AlterModelOptions(
            name='tekliresim',
            options={'ordering': ('isim',), 'verbose_name': 'Resim', 'verbose_name_plural': 'Resimler'},
        ),
        migrations.AlterField(
            model_name='anacategory',
            name='aktif',
            field=models.BooleanField(help_text='Sitede görünmesini istemiyorsanız işaretleyiniz!!!', verbose_name='Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='anacategory',
            name='bireysel_mi',
            field=models.BooleanField(help_text='Öğrencilerle beraber oynanMAyacaksa işaretlenecek!!!', verbose_name='Bireysel mi'),
        ),
        migrations.AlterField(
            model_name='anacategory',
            name='sadece_madalyalı_mı',
            field=models.BooleanField(help_text='Herhangi bir oyun olmaksızın bir kategori ise işaretlenecek Örneğin; sadece madalya için', verbose_name='Etkinliksiz madalyalı mı'),
        ),
        migrations.AlterField(
            model_name='anacategory',
            name='sayfa_durumu',
            field=models.BooleanField(help_text='1500-2500 gibi sayfa sayısı varsa işaretlenecek', verbose_name='Sayfa Sayısı Var mı?'),
        ),
        migrations.AlterField(
            model_name='anacategory',
            name='slug',
            field=models.SlugField(help_text='Burası yalnızca site-dizaynı için. Dokunmayınız!', max_length=150, unique=True, verbose_name='internet adresi'),
        ),
    ]
