# Generated by Django 2.0 on 2019-07-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20190702_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='anasayfada_gosterilsin_mi',
            field=models.BooleanField(default=True, help_text='Anasayfada gösterilmesi istenen ürünler için işaretlenecektir.', verbose_name='AnaSayfada gösterilsin mi?'),
        ),
        migrations.AlterField(
            model_name='anacategory',
            name='aktif',
            field=models.BooleanField(help_text='Sitede görünmesini istiyorsanız işaretleyiniz!!!', verbose_name='Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='anacategory',
            name='sadece_madalyalı_mı',
            field=models.BooleanField(help_text='Herhangi bir oyun olmaksızın bir kategori ise işaretlenecek Örneğin; sadece madalya için', verbose_name='Sadece Madalya mı'),
        ),
    ]
