# Generated by Django 2.0 on 2019-07-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20190702_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='anasayfada_gosterilsin_mi',
        ),
    ]
