# Generated by Django 2.0 on 2019-07-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_product_anasayfada_gosterilsin_mi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anacategory',
            name='aktif',
            field=models.BooleanField(default=False, help_text='Sitede görünmesini istiyorsanız işaretleyiniz!!!', verbose_name='Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='anacategory',
            name='bireysel_mi',
            field=models.BooleanField(default=False, help_text='Öğrencilerle beraber oynanMAyacaksa işaretlenecek!!!', verbose_name='Bireysel mi'),
        ),
        migrations.AlterField(
            model_name='anacategory',
            name='sadece_madalyalı_mı',
            field=models.BooleanField(default=False, help_text='Herhangi bir oyun olmaksızın bir kategori ise işaretlenecek Örneğin; sadece madalya için', verbose_name='Sadece Madalya mı'),
        ),
        migrations.AlterField(
            model_name='anacategory',
            name='sayfa_durumu',
            field=models.BooleanField(default=False, help_text='1500-2500 gibi sayfa sayısı varsa işaretlenecek', verbose_name='Sayfa Sayısı Var mı?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='madalyalı_mı',
            field=models.BooleanField(default=True, verbose_name='Madalyalı mı'),
        ),
    ]
