# Generated by Django 2.0 on 2019-07-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20190703_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='aktif',
            field=models.BooleanField(default=False, help_text='Sitede görünmesini istiyorsanız işaretleyiniz!!!', verbose_name='Aktif mi?'),
        ),
        migrations.AddField(
            model_name='product',
            name='aktif',
            field=models.BooleanField(default=False, help_text='Sitede görünmesini istiyorsanız işaretleyiniz!!!', verbose_name='Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='agırlık',
            field=models.FloatField(default=0, verbose_name='Ağırlık'),
        ),
    ]
