# Generated by Django 2.0 on 2019-09-08 18:09

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='İrtibat Numarası', max_length=31, verbose_name='Telefon No:'),
        ),
    ]
