# Generated by Django 2.0 on 2019-09-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, help_text='İrtibat Numarası', max_length=11, verbose_name='Telefon No:'),
        ),
    ]
