# Generated by Django 2.0 on 2019-08-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='siparis_durumu',
            field=models.CharField(blank=True, choices=[('1', 'İşlemde'), ('2', 'Hazırlanıyor'), ('3', 'Kargoya Teslim Edildi')], max_length=10, verbose_name='Sipariş Durumu:'),
        ),
        migrations.AddField(
            model_name='order',
            name='siparis_notu',
            field=models.TextField(blank=True, verbose_name='Sipariş_notu:'),
        ),
    ]
