# Generated by Django 2.0 on 2019-09-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, help_text='İrtibat Numarası', max_length=11, verbose_name='Telefon No:'),
        ),
    ]
