# Generated by Django 2.0 on 2019-09-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190910_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='siparis_durumu',
            field=models.CharField(choices=[('1', 'İşlemde'), ('2', 'Hazırlanıyor'), ('3', 'Kargoya Teslim Edildi'), ('4', 'İptal')], default='1', max_length=10, verbose_name='Sipariş Durumu:'),
        ),
    ]
