# Generated by Django 2.0 on 2019-08-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190806_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='siparis_durumu',
            field=models.CharField(choices=[('1', 'İşlemde'), ('2', 'Hazırlanıyor'), ('3', 'Kargoya Teslim Edildi')], default='1', max_length=10, verbose_name='Sipariş Durumu:'),
        ),
    ]
