# Generated by Django 2.0 on 2019-11-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191101_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='agırlık',
            field=models.FloatField(default=0, verbose_name='Ağırlık'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Miktar'),
        ),
    ]
