# Generated by Django 2.0 on 2019-08-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_indirim_tutari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='siparis_notu',
            field=models.TextField(blank=True, verbose_name='Sipariş Notu:'),
        ),
    ]
