# Generated by Django 2.0 on 2019-08-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190807_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='kargo_tipi',
            field=models.CharField(choices=[('1', 'Kapıda Nakit Ödeme'), ('2', 'Kapıda Tek Çekim Kredi Kartı Ödeme'), ('3', 'Havale/EFT')], help_text='Blabla', max_length=10, verbose_name='Ödeme Tercihiniz:'),
        ),
    ]
