# Generated by Django 2.0 on 2019-08-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190810_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='toplam_urun_tutarı',
            field=models.PositiveIntegerField(default=0, verbose_name='Ürün bedeli'),
        ),
    ]
